Billsplitter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^accounts/Expense/", include("Expense.urls")),

]

Expense/urls.py
from django.urls import path,re_path
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'Expense'

urlpatterns = [
	path('TotalExpenes/',ExpenseListAPIView ,name="expenses"),
	path('del/',ExpenseDelView),
	path('addexpense/',ExpenseAddAPIView,name='addexpense'),
	path('GroupExpenses/',AllGroups,name='groups'),
	path('AddGroup/',Add_Group,name='Add_groups'),	
	re_path(r'^GroupExpenses/(?P<id>[0-9]+)/Add_user/',Add_user_view,name='Add_user'),
	re_path(r'^GroupExpenses/(?P<id>[0-9]+)$',GroupExpenseView,name='group_expenses'),
	re_path(r'^addGroupexpense/(?P<id>[0-9]+)$',GroupExpenseAddAPIView ,name="addgroupexpenses"),
	]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'accounts'

urlpatterns = [
path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
path('logout/',auth_views.LogoutView.as_view(),name='logout'),
path('signup/',views.SignUp.as_view(),name='signup')
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>

    <meta charset="utf-8">
    <title>Split-wisely</title>


    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>



    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href={% static 'simplesocial/css/master.css'%}>


<style type="text/css">
  
  @import 'https://fonts.googleapis.com/css?family=Montserrat:300,400,700';

body {
  font-family: Montserrat, sans-serif;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  color: #000;
  background: #eee;
}
h1 {
  font-weight: normal;
  letter-spacing: -1px;
  color: #34495E;
}
.table {
  background: #34495E;
  color: #fff;
  border-radius: .4em;
  overflow: hidden;
}
  tr {
    border-color: lighten(#34495E, 10%);
  }
  th, td {
    margin: .5em 1em;
    @media (min-width: $breakpoint-alpha) { 
      padding: 1em !important; 
    }
  }
  th, td:before {
    color: #dd5;
  }

  .input-phone{
  display: inline-block;
  margin: 1em auto;
  padding: 0.5em;
  border: none;
  border-radius: 0.2em;
  font-size: 1.5em;
  box-shadow: 0 0 1em 0.25em rgba(0,0,0,0.2);
}


button {
  outline:none;
  height: 40px;
  text-align: center;
  width: 130px;
  border-radius:40px;
  background: #fff;
  border: 2px solid #1ECD97;
  color:#1ECD97;
  letter-spacing:1px;
  text-shadow:0;
  font:{
    size:12px;
    font-weight:bold;
}
 

</style>
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-150269407-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-150269407-1');
</script>


  </head>


  <body>

    <nav class="navbar-inverse  mynav " role="navigation" id="navbar" style="color: white;" >
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Split Wisely</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="{% url 'Expense:Add_groups' %}"class="btn btn-simple">Add Groups</a></li>            
                      <li><a href="{% url 'Expense:groups' %}"class="btn btn-simple">Groups</a></li>
                      <li><a href="{% url 'Expense:expenses' %}" class="btn btn-simple">Expenses</a></li> 
                      <li><a href="{% url 'Expense:addexpense' %}" class="btn btn-simple">Add Expenses</a></li> 
                      <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>
    						      <li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>  
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas">

</canvas>



  </body>
<script type="text/javascript">
$(function() {
  $( "#button" ).click(function() {
    $( "#button" ).addClass( "onclic", 250, validate);
  });

  function validate() {
    setTimeout(function() {
      $( "#button" ).removeClass( "onclic" );
      $( "#button" ).addClass( "validate", 450, callback );
    }, 2250 );
  }
    function callback() {
      setTimeout(function() {
        $( "#button" ).removeClass( "validate" );
      }, 1250 );
    }
  });
  </script>


  <script src="{% static "/simplesocial/js/master.js" %}" type="text/javascript" ></script>


  <script type="text/javascript">
    function check(elem) {
    // use one of possible conditions
    // if (elem.value == 'Other')
    if (elem.value == 'Multiple-Users') {
        document.getElementById("other-div").style.display = 'block';
    } else {
        document.getElementById("other-div").style.display = 'none';
    }
}
  </script>
  <script type="text/javascript">
    $(".rename").click(function(e){
  e.preventDefault();
  var $this = $(this);
  var fileName = $(this).data("file");
    $("#basicModal").data("fileName", fileName).modal("toggle", $this);
});
  $(".sename").click(function(e){
  e.preventDefault();
  var $this = $(this);
  var fileName = $(this).data("file");
  $("#UserModal").data("fileName", fileName).modal("toggle", $this);
});
    $(".blnc").click(function(e){
  e.preventDefault();
  var $this = $(this);
  var fileName = $(this).data("file");
  $("#Balance").data("fileName", fileName).modal("toggle", $this);
});
  $(".NNblnc").click(function(e){
  e.preventDefault();
  var $this = $(this);
  var fileName = $(this).data("file");
  $("#SHB").data("fileName", fileName).modal("toggle", $this);
});
        
  </script>


  
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1 style="position: relative; top:200px; left:375px;">Welcome to <strong>Split-Wisely</strong></h1>
    
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>you are logged in !</h1>
    <h1 style="position: relative; top:200px; left:375px;">Welcome to <strong>Split-Wisely</strong></h1>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting,come backsoon!</h1>
<h1 style="position: relative; top:200px; left:375px;"><strong>Split-Wisely</strong></h1>
{% endblock %}